db_postgres:
  outputs:
    dev:
      dbname: mlops_movie
      host: localhost
      pass: mysecretpassword
      port: 5432
      schema: target
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbt_mlops:
  outputs:
    dev:
      dbname: mlops
      host: localhost
      pass: mysecretpassword
      port: 5432
      schema: target
      threads: 1
      type: postgres
      user: postgres
  target: dev
